### PR TITLE
github credentials in environment, and code reorganization

### PR DESCRIPTION
**Pull request by jjb**
Here's a patch that reads github credentials from the shell environment if they are there (I don't like to keep mine in my .gitconfig because i have my .gitconfig checked into a public repo[1]).

I've also reorganized the code into a common library.

Let me know what you think!
John

[1]https://github.com/jjb/dotfiles

### CODE REVIEW

**Comment by ivanvc** [comment]
Hey John,

This is a great addition. However, am thinking that we should support both, since even that I have my dot files in a public repo, I didn't add my [.gitconfig actual file](https://github.com/ivanvc/dotfiles/blob/master/gitconfig.erb), just a template. And also I like to have my token globally, since some other github tools read the token from there. So, what do you think about supporting both?

**Comment by jjb** [comment]
Hi Iván. My patch does indeed already support both :-) It looks in environment first, and then in gitconfig.

```
@login = ENV['GITHUB_USER']  || `#{github_config_get}.user`.chomp
@token = ENV['GITHUB_TOKEN'] || `#{github_config_get}.token`.chomp
```

:-)

**Comment by jjb** [comment]
Hi ivanvc. Is that sufficient?

**Comment by ivanvc** [comment]
Hey John,

Am really sorry for the delay. Applying your commit right now.

**Comment by jjb** [comment]
No worries. Awesome! :-D I have recently discovered that reading the variables from the environment doesn't work if the user opens textmate from the dock or Finder. it has to be opened from the `mate` command in order to pick up the environment variables. really strange behavior on TextMate's part.

I'll add this to the readme

**Comment by ivanvc** [comment]
Great! this time I promise the merge will be done faster, hehe.

**Pull request merged**
